import "@css/plugins/bootstrap-grid.css";
import { Atkinson_Hyperlegible, Space_Grotesk } from "next/font/google";
import Script from "next/script";

import "@css/plugins/swiper.min.css";
// Only the icons the site uses — regenerate with scripts/subset-icons.py.
import "@fonts/font-awesome/css/fa-subset.css";

import "@scss/style.css";

const atkinson = Atkinson_Hyperlegible({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--font-atkinson',
  display: 'swap',
})

const space_grotest = Space_Grotesk({
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-space-grotesk',
  display: 'swap',
})

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  viewportFit: 'cover',
  userScalable: 0,
  themeColor: [
    { media: '(prefers-color-scheme: dark)', color: '#000000' },
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
  ],
}

const SITE_DESCRIPTION = "Cyril Florita's professional website showcasing his background, skills, experience, and projects as a designer and developer.";
// Generated by `npm run og` (scripts/make-og.mjs).
const DEFAULT_SHARE_IMAGE = { url: '/og/default.jpg', width: 1200, height: 630, alt: 'Cyril Florita' };

export const metadata = {
  metadataBase: new URL('https://cyrilflorita.com'),
  title: {
    default: 'Cyril Florita — Designer and Developer',
    template: '%s — Cyril Florita',
  },
  description: SITE_DESCRIPTION,
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    siteName: 'Cyril Florita',
    locale: 'en_US',
    url: '/',
    title: 'Cyril Florita — Designer and Developer',
    description: SITE_DESCRIPTION,
    images: [DEFAULT_SHARE_IMAGE],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Cyril Florita — Designer and Developer',
    description: SITE_DESCRIPTION,
    images: [DEFAULT_SHARE_IMAGE.url],
  },
  icons: {
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  }
};

import { ClientThemeProvider } from '../components/ClientThemeProvider';
import Preloader from '../components/Preloader';

// Social profiles match the links in layout/Footer.js.
const PERSON_JSON_LD = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: 'Cyril Florita',
  jobTitle: 'Designer and Developer',
  url: 'https://cyrilflorita.com/',
  image: 'https://cyrilflorita.com/img/cyril-florita-profile.png',
  sameAs: [
    'https://www.behance.net/cyrilflorita',
    'https://github.com/cyril-florita',
    'https://www.linkedin.com/in/cyrilflorita',
    'https://x.com/CyrilFlorita',
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark" className={`${space_grotest.variable} ${atkinson.variable}`} suppressHydrationWarning={true}>
      <head>
        {/* Set theme before first paint (default dark) to avoid a flash on navigation */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function () {
                try {
                  var theme = localStorage.getItem('theme') || 'dark';
                  document.documentElement.setAttribute('data-theme', theme);
                } catch (e) {}
              })();
            `,
          }}
        />
        {/* Structured data: who this site is about */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(PERSON_JSON_LD) }}
        />
      </head>
      <body className="cyril-custom-scroll" suppressHydrationWarning={true}>
        <Preloader />
        {/* Google Analytics */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-QQM967TF9Z"
        />
        <Script
          id="google-analytics-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-QQM967TF9Z');
            `,
          }}
        />
        <ClientThemeProvider>{children}</ClientThemeProvider>
      </body>
    </html>
  );
}