// Emitted as out/manifest.webmanifest by the static export. Icons are
// generated by `npm run og` (scripts/make-og.mjs).
export const dynamic = 'force-static';

export default function manifest() {
  return {
    name: 'Cyril Florita — Designer and Developer',
    short_name: 'Cyril',
    start_url: '/',
    display: 'standalone',
    background_color: '#000000',
    theme_color: '#000000',
    icons: [
      { src: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
  };
}
