import SIZES from "@/components/data/imageSizes.json";

// <img> props for a portfolio image: the 800w WebP thumbnail as src, a srcset
// that adds the 1600w WebP for large/retina displays, and the original's
// intrinsic width/height so the browser reserves the right space before it
// loads. Generated by `npm run thumbs` (scripts/make-thumbs.mjs); images
// without an entry fall back to the original file. `sizes` should describe
// how wide the image is displayed.
const SMALL = 800;
const LARGE = 1600;

export const thumbFor = (src, large = false) =>
  src.replace("/img/portfolio/", "/img/thumbs/portfolio/").replace(/\.(jpe?g|png)$/i, large ? `@${LARGE}.webp` : ".webp");

export const imageSize = (src) => SIZES[src] || null;

export const imageProps = (src, sizes = "100vw") => {
  const size = SIZES[src];
  if (!size) return { src };
  const [w, h] = size;
  const props = { src: thumbFor(src), width: w, height: h };
  if (w > SMALL) {
    props.srcSet = `${thumbFor(src)} ${SMALL}w, ${thumbFor(src, true)} ${Math.min(LARGE, w)}w`;
    props.sizes = sizes;
  }
  return props;
};

// Display-width hints for the common layouts.
export const SIZES_HINT = {
  gridTile: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 420px",
  full: "(max-width: 1200px) 100vw, 1000px",
  text: "(max-width: 768px) 100vw, 700px",
  two: "(max-width: 768px) 100vw, 500px",
  three: "(max-width: 576px) 100vw, (max-width: 992px) 50vw, 330px",
  half: "(max-width: 1200px) 100vw, 40vw",
};
