"""Subset Font Awesome to the icons the site actually uses.

    python3 scripts/subset-icons.py   (needs: pip install fonttools brotli)

Scans app/, components/, layout/ and the SCSS for fa-* icon classes, looks up
their codepoints in the full Font Awesome stylesheet, and writes:
  public/fonts/font-awesome/webfonts/fa-solid-subset.woff2
  public/fonts/font-awesome/webfonts/fa-brands-subset.woff2
  public/fonts/font-awesome/css/fa-subset.css   (imported by app/layout.js)
Re-run after using a new icon; the full all.min.css + fonts stay in the repo
as the source.
"""
import re, pathlib
from fontTools import subset

ROOT = pathlib.Path(__file__).resolve().parent.parent
FA = ROOT / "public/fonts/font-awesome"
css = (FA / "css/all.min.css").read_text()

# Icon classes used anywhere in the markup or styles.
used = set()
for folder in ("app", "components", "layout", "public/scss"):
    for f in (ROOT / folder).rglob("*"):
        if f.suffix in (".js", ".scss"):
            used |= set(re.findall(r"\bfa-([a-z0-9-]+)", f.read_text(errors="ignore")))
STYLE_WORDS = {"solid", "brands", "regular"}
names = sorted(n for n in used - STYLE_WORDS if re.search(r"\.fa-%s\{--fa:" % re.escape(n), css))

codepoints = {n: re.search(r'\.fa-%s\{--fa:"\\([0-9a-f]+)"' % re.escape(n), css).group(1) for n in names}

def build(src, out, cps):
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.layout_features = []
    font = subset.load_font(str(src), opts)
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=[int(c, 16) for c in cps])
    sub.subset(font)
    subset.save_font(font, str(out), opts)

cps = sorted(set(codepoints.values()))
build(FA / "webfonts/fa-solid-900.woff2", FA / "webfonts/fa-solid-subset.woff2", cps)
build(FA / "webfonts/fa-brands-400.woff2", FA / "webfonts/fa-brands-subset.woff2", cps)

rules = "".join('.fa-%s{--fa:"\\%s"}' % (n, codepoints[n]) for n in names)
(FA / "css/fa-subset.css").write_text(
    "/* Generated by scripts/subset-icons.py — Font Awesome Free 6.7.2 subset "
    "(Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT). Icons: %s */\n" % ", ".join(names)
    + '@font-face{font-family:"Font Awesome 6 Free";font-style:normal;font-weight:900;font-display:block;src:url(../webfonts/fa-solid-subset.woff2) format("woff2")}\n'
    + '@font-face{font-family:"Font Awesome 6 Brands";font-style:normal;font-weight:400;font-display:block;src:url(../webfonts/fa-brands-subset.woff2) format("woff2")}\n'
    + '.fa,.fas,.fa-solid{font-family:"Font Awesome 6 Free";font-weight:900}\n'
    + '.fab,.fa-brands{font-family:"Font Awesome 6 Brands";font-weight:400}\n'
    + ".fa,.fab,.fas,.fa-solid,.fa-brands{-moz-osx-font-smoothing:grayscale;-webkit-font-smoothing:antialiased;display:var(--fa-display,inline-block);font-style:normal;font-variant:normal;line-height:1;text-rendering:auto}\n"
    + ".fa:before,.fab:before,.fas:before,.fa-solid:before,.fa-brands:before{content:var(--fa)}\n"
    + rules + "\n"
)
print(len(names), "icons:", ", ".join(names))
for f in ("webfonts/fa-solid-subset.woff2", "webfonts/fa-brands-subset.woff2", "css/fa-subset.css"):
    print(f, (FA / f).stat().st_size, "bytes")
